<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BajuTahanPanasSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['nama_penerima' => 'M. Sanusi Andrian', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Abdul Muthalib. Hs', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Ade Firnanda Rivai', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Adriansyah', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Wiyoto', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Amir Hamza', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Arif Masdianto', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Aulia Rahman', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Febri Roziardy Putra', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Feri Isharianto', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Hendra. S', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Ja’i', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'M. Sujarkoni', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Munir Riyadi', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Nurpan Taupan', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Poniadi', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Saiful Mustofa', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Suprapto', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Wagimin', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Wakijan', 'warna_baju' => 'Coklat', 'tahun_baju' => 2026, 'helm' => 1, 'tahun_helm' => 2026, 'keterangan' => ''],
            ['nama_penerima' => 'Suci Fitriyanto', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Deden Ramadhan', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Eko Perdana', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Suherman', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Riawan', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Wahyudi', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Irfan Wahyudi', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Rudi Ariandi', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'M. Hidayat', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Hari Sabta ', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Indriyanto', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Paryono', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'M. Deni Pranata', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Ranu Prasetio', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Surandi Maulana', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Reza Eko ', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Basopi', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Hariyanto', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Suryadi', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'A. Fanani', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Adi Putra', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Ishak Effendi', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Andi Setiawan', 'warna_baju' => 'Biru', 'tahun_baju' => 2025, 'helm' => 1, 'tahun_helm' => 2025, 'keterangan' => ''],
            ['nama_penerima' => 'Jhon Husairi', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Fadli', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Syafiq', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Hasanudin', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Rudi Utoyo', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Edi Susilo', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Muhammad Rio', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Muslim', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Adi Khiyoto', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Rifo Nofriadi', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Dedi Agung. P', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M Idrus', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Febri Harmono', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Kholid', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Heri Hidayat', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Riyan Febriatnto', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Danil Akbar', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Masrizal', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Riky Restiawan', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Arifin', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Misbah', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M. Arif Wahyudi', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Darmawan', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Ridho Dazrizal ', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Ferdinand Ronaldo T', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Fahrizal', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Iwan Effendi', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Imron', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Nanda', 'warna_baju' => 'Biru', 'tahun_baju' => 2024, 'helm' => 1, 'tahun_helm' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M. Ilham Ardhy', 'warna_baju' => 'Orange', 'tahun_baju' => 2023, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Mardian Hasnur', 'warna_baju' => 'Orange', 'tahun_baju' => 2023, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Pendi Abdullah', 'warna_baju' => 'Orange', 'tahun_baju' => 2023, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Nasir', 'warna_baju' => 'Orange', 'tahun_baju' => 2023, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Siswanto', 'warna_baju' => 'Orange', 'tahun_baju' => 2023, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Sutarto', 'warna_baju' => 'Orange', 'tahun_baju' => 2023, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ilham Saputra', 'warna_baju' => 'Orange', 'tahun_baju' => 2023, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Teguh Leksono', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Abdul Syukur', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Muji Harnadi', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Husnul Mubarok', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dimas Wahyu. K', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Slamet', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Bayu Sukma', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Arif ', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Vicky', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Redi Julian', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Edi Marjoko', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Amid Jaya', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Nur Ruwanda', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Firdaus', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Bambang Sugiono', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Isnaini', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dedi Thoblawi', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Taufik', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Teguh Sufriyanto', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ardiyanto', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Bunnari', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'David Hermansyah', 'warna_baju' => 'Orange', 'tahun_baju' => 2022, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Riman Jaya', 'warna_baju' => 'Orange', 'tahun_baju' => 2021, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Zakirin', 'warna_baju' => 'Orange', 'tahun_baju' => 2021, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Herman Yanto', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Kms. Muammar', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dwi Wahyudi', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Wilopo', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Wendo. AR', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ahmad Yani', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Benni', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Yahya', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Furqon', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Kardela', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Rahmad Veri Riski', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ahmad Sukri Insani', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Bambang Apriadi', 'warna_baju' => 'Merah', 'tahun_baju' => 2020, 'helm' => 0, 'tahun_helm' => null, 'keterangan' => ''],
        ];

        // Memasukkan array ke dalam tabel database
        DB::table('baju_tahan_panas')->insert($data);
    }
}