<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HidranKotaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'jalan' => 'Jl. Slamet riyadi',
                'kecamatan' => 'Danau sipin',
                'kelurahan' => 'Murni',
                'rt' => '-',
                'lokasi_terdekat' => 'Depan musium perjuangan',
                'kode_map' => 'CJ34+MWG',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln. Mayjen HM.J Singedekane',
                'kecamatan' => 'Danau Sipin',
                'kelurahan' => 'Sungai Putri',
                'rt' => '-',
                'lokasi_terdekat' => 'depan Telkom sto telanai',
                'kode_map' => '9HVQ+9V5',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln. Urip Sumoharjo',
                'kecamatan' => 'Danau Sipin',
                'kelurahan' => 'Sungai Putri',
                'rt' => '13',
                'lokasi_terdekat' => 'Depan Musium Negeri Jambi',
                'kode_map' => '9HRR+RXR',
                'kondisi_hidran' => 'Baik',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jl selamet riyadi',
                'kecamatan' => 'Danau Sipin',
                'kelurahan' => 'Legok',
                'rt' => '24',
                'lokasi_terdekat' => 'Lorong remaja',
                'kode_map' => 'CH2X+88F',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'jln. Jendral Urip Somoharjo',
                'kecamatan' => 'Danau sipin',
                'kelurahan' => 'Selamet',
                'rt' => '-',
                'lokasi_terdekat' => 'Di halaman rumah dinas BPK',
                'kode_map' => '9HQV+CFX',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => null,
                'machino' => null,
                'keterangan' => 'Tidak Bisa Dipakai/ Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jln. Sumantri Brojonegoro',
                'kecamatan' => 'Danau Sipin',
                'kelurahan' => 'Payo lebar',
                'rt' => '35',
                'lokasi_terdekat' => 'depan smu Ferdi Fery',
                'kode_map' => '9HVX+6QG',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jln. Nanas ',
                'kecamatan' => 'Pasar Jambi',
                'kelurahan' => 'Beringin',
                'rt' => '16',
                'lokasi_terdekat' => 'sebelah mes TNI',
                'kode_map' => 'CJ45+JXV',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Lemah',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jln.Raden Pamuk',
                'kecamatan' => 'pasar jambi',
                'kelurahan' => 'Beringin',
                'rt' => '17',
                'lokasi_terdekat' => 'depan ex BTN/angso duo',
                'kode_map' => 'CJ56+69V',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'lorong  merpati',
                'kecamatan' => 'pasar jambi',
                'kelurahan' => 'Beringin',
                'rt' => '08',
                'lokasi_terdekat' => 'Sebelah pos jaga masjid',
                'kode_map' => 'CJ35+795',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln Husni Thamrin ',
                'kecamatan' => 'pasar jambi',
                'kelurahan' => 'Beringin',
                'rt' => '13',
                'lokasi_terdekat' => 'Sebrang hotel Makmur',
                'kode_map' => 'CJ46+6CH',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln. Diponegoro',
                'kecamatan' => 'Pasar Jambi',
                'kelurahan' => 'Sungai asam',
                'rt' => '08',
                'lokasi_terdekat' => 'Sebrang yayasan Amitaba',
                'kode_map' => '9JX9+JMQ',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => 'Sedang',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Machino Rusak',
            ],
            [
                'jalan' => 'Jln. Prof Hmo Bafadhal',
                'kecamatan' => 'Pasar Jambi',
                'kelurahan' => 'Sungai asam',
                'rt' => '02',
                'lokasi_terdekat' => 'Sebrang JLN. EX Hotel Novita',
                'kode_map' => 'CJ37+GRX',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln DR Wahidin ',
                'kecamatan' => 'Pasar Jambi',
                'kelurahan' => 'Orang kayo hitam',
                'rt' => '04',
                'lokasi_terdekat' => 'Simpang Bata',
                'kode_map' => 'CJ48+W69',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => 'Lemah',
                'machino' => 'Baik',
                'keterangan' => 'Tidak Bisa Dipakai/ Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jln. Samratulagi',
                'kecamatan' => 'Pasar jambi',
                'kelurahan' => 'Pasar',
                'rt' => '05',
                'lokasi_terdekat' => 'Taman ria',
                'kode_map' => 'CJ58+498',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => 'Lemah',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jln Hoscokro aminoto',
                'kecamatan' => 'Kota Baru',
                'kelurahan' => 'Suka karya',
                'rt' => '-',
                'lokasi_terdekat' => 'Halaman mako damkar',
                'kode_map' => '9JJ2+Q24',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'jln agus salim',
                'kecamatan' => 'Kota Baru',
                'kelurahan' => 'Pall lima',
                'rt' => '10',
                'lokasi_terdekat' => 'Depan TR Futsal',
                'kode_map' => '9J86+8W8',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln. Pendidikan',
                'kecamatan' => 'Kota Baru',
                'kelurahan' => 'Mayang mangurai',
                'rt' => '08',
                'lokasi_terdekat' => 'Depan Rumah Pribadi Sekda',
                'kode_map' => '9H4Q+292',
                'kondisi_hidran' => 'Baik',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Machino Rusak',
            ],
            [
                'jalan' => 'Jln. Hayam Wuruk ',
                'kecamatan' => 'Jelutung ',
                'kelurahan' => 'Cempaka putih',
                'rt' => '14',
                'lokasi_terdekat' => 'Depan toko saga pasar Hongkong',
                'kode_map' => '9JW8+CVC',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => 'Lemah',
                'machino' => 'Baik',
                'keterangan' => 'Tidak Bisa Dipakai/ Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jln.Prof M Yamin',
                'kecamatan' => 'Jelutung',
                'kelurahan' => 'Payo lebar',
                'rt' => '18',
                'lokasi_terdekat' => 'Depan Hotel Aini',
                'kode_map' => '9JQ3+JG2',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Machino Rusak',
            ],
            [
                'jalan' => 'Jln. KH Msaleh',
                'kecamatan' => 'Danau teluk',
                'kelurahan' => 'Pasir Panjang',
                'rt' => '02',
                'lokasi_terdekat' => 'PDAM Pasir Panjang',
                'kode_map' => 'CH9G+J58',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln Kompol Ahmad Bastari',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '01',
                'lokasi_terdekat' => 'simpang kantor camat',
                'kode_map' => 'CJ4H+H8C',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tidak keluar Air',
            ],
            [
                'jalan' => 'Jln. Taruma Negara',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '12',
                'lokasi_terdekat' => 'depan KUA Jambi Timur',
                'kode_map' => 'CJ5J+QXP',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jln Orang Kayo Hitam',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Sulanjana',
                'rt' => '03',
                'lokasi_terdekat' => 'simpang masuk terminal RS',
                'kode_map' => 'CJ49+3VV',
                'kondisi_hidran' => 'Baik',
                'tekanan' => null,
                'machino' => 'Baik',
                'keterangan' => 'Tidak Bisa Dipakai/ Tidak keluar Air',
            ],
            [
                'jalan' => 'Jln. Orang Kayo Hitam',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Sulanjana',
                'rt' => '03',
                'lokasi_terdekat' => 'simpang hotel evan',
                'kode_map' => 'CJ3C+Q8V',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tidak keluar Air',
            ],
            [
                'jalan' => 'Jln Fatmawati ',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Kasang',
                'rt' => '01',
                'lokasi_terdekat' => 'sebelah rumdis Sekda Prov',
                'kode_map' => 'CJ79+3F',
                'kondisi_hidran' => 'Baik',
                'tekanan' => null,
                'machino' => 'Baik',
                'keterangan' => 'Tidak Bisa Dipakai/ Tidak keluar Air',
            ],
            [
                'jalan' => 'Jln. Singasari',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '17',
                'lokasi_terdekat' => 'di belakang pos ',
                'kode_map' => 'CJ4P+3JV',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Lemah',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa dipakai /Machino Rusak',
            ],
            [
                'jalan' => 'Lrg. Garuda Gapura Merah',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Talang Banjar',
                'rt' => '29',
                'lokasi_terdekat' => 'Simpang Dalam ',
                'kode_map' => 'CJ5J+893',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tidak keluar Air',
            ],
            [
                'jalan' => 'JL. Kompol Ahmad Bastari',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '11',
                'lokasi_terdekat' => 'Sebelah Mesjid Nurul Hikmah',
                'kode_map' => 'CJ5H+8QG',
                'kondisi_hidran' => 'Baik',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai/ Tidak keluar Air',
            ],
            [
                'jalan' => 'Jln. Prabu siliwangi',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '20',
                'lokasi_terdekat' => 'depan pos damkar',
                'kode_map' => 'CJ5P+VPF',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'JL. Orang Kayo Pinai',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Budiman ',
                'rt' => '16',
                'lokasi_terdekat' => 'Lampu Merah',
                'kode_map' => 'CJ2H+Q3 ',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai /Machino Rusak',
            ],
            [
                'jalan' => 'Jl. Mayor ABD. Karta Wirana',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Budiman ',
                'rt' => '14',
                'lokasi_terdekat' => 'Lrg. Budiman ',
                'kode_map' => 'CJ3F+7VW',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai /Machino Rusak',
            ],
            [
                'jalan' => 'Jl. Gr.Djamin Datuk Bagindo',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Talang Banjar',
                'rt' => '06',
                'lokasi_terdekat' => 'Indomart',
                'kode_map' => 'CJ2H+22 ',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai/Kode Map Tidak Sesuai ',
            ],
            [
                'jalan' => 'Jl. Bhayangkara',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Talang Banjar',
                'rt' => '13',
                'lokasi_terdekat' => 'Simpang Meranti',
                'kode_map' => '9JWH+86V',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jl. Pakubuwono/saman',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '22',
                'lokasi_terdekat' => 'belakang Pasar Baru Lama',
                'kode_map' => 'CJ3M+558',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Jl. Pakubuwono',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '33',
                'lokasi_terdekat' => 'SD 121',
                'kode_map' => 'CJ3M+FR ',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Rusak',
                'keterangan' => 'Bisa Dipakai/Kode Map Tidak Sesuai ',
            ],
            [
                'jalan' => 'Lrg. Mat Beken ',
                'kecamatan' => 'Jambi timur',
                'kelurahan' => 'Tanjung Pinang',
                'rt' => '13',
                'lokasi_terdekat' => 'Seberang Puskesmas',
                'kode_map' => 'CJ6J+3J3',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai /Machino Rusak',
            ],
            [
                'jalan' => 'Prabu Siliwangi',
                'kecamatan' => 'Jambi Timur',
                'kelurahan' => 'Tanjung Sari',
                'rt' => '23',
                'lokasi_terdekat' => '-',
                'kode_map' => '-',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai/ Tidak Ada Kode Map',
            ],
            [
                'jalan' => 'Jln. RB siagian',
                'kecamatan' => 'Pallmerah',
                'kelurahan' => 'Talang Bakung',
                'rt' => '16',
                'lokasi_terdekat' => 'Posyankar Pallmerah',
                'kode_map' => '9M93+9PR',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Pos yankar alam barajo',
                'kecamatan' => 'Alam Barajo',
                'kelurahan' => 'Rawasari',
                'rt' => '25',
                'lokasi_terdekat' => 'Posyankar Alam barajo',
                'kode_map' => '9HGG+H2V',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Kuat',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'Lorong Patimura',
                'kecamatan' => 'Alam Barajo',
                'kelurahan' => 'Kenali besar',
                'rt' => '13',
                'lokasi_terdekat' => 'sebelah lorong jaya',
                'kode_map' => '9HH2+JFJ',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Lemah',
                'machino' => 'Baik',
                'keterangan' => 'Tidak Bisa Dipakai/Tekanan Air Lemah',
            ],
            [
                'jalan' => 'Jln Lingkar Barat',
                'kecamatan' => 'Alam Barajo',
                'kelurahan' => 'Kenali besar',
                'rt' => '35',
                'lokasi_terdekat' => 'Sebelah pos Masuk terminal',
                'kode_map' => '9HC2+GGF',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai',
            ],
            [
                'jalan' => 'jl. Kh zuhdi',
                'kecamatan' => 'pelayanagan',
                'kelurahan' => 'Mudung Laut',
                'rt' => '-',
                'lokasi_terdekat' => 'IPA P Panjang',
                'kode_map' => 'CJHF+X3P',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai ',
            ],
            [
                'jalan' => 'Jl. Kh. A. Majid',
                'kecamatan' => 'pelayangan',
                'kelurahan' => 'Tanjung Johor',
                'rt' => '-',
                'lokasi_terdekat' => 'IPA t Johor',
                'kode_map' => 'CJMG+HR8',
                'kondisi_hidran' => null,
                'tekanan' => 'Sedang',
                'machino' => null,
                'keterangan' => 'Mengisi Mengunakan Pompa',
            ],
            [
                'jalan' => 'Jl. Kh somad',
                'kecamatan' => 'pelayangan',
                'kelurahan' => 'Olak Kemang',
                'rt' => '-',
                'lokasi_terdekat' => 'IPA t Johor',
                'kode_map' => 'CJ92+HW7',
                'kondisi_hidran' => 'Baik',
                'tekanan' => 'Sedang',
                'machino' => 'Baik',
                'keterangan' => 'Bisa Dipakai /Tergantung listrik',
            ],
            [
                'jalan' => 'Jl. Kh Somad',
                'kecamatan' => 'Pelayangan',
                'kelurahan' => 'Arab Melayu',
                'rt' => null,
                'lokasi_terdekat' => 'IPA t Johor',
                'kode_map' => 'CJ97+27X',
                'kondisi_hidran' => 'Rusak',
                'tekanan' => null,
                'machino' => 'Rusak',
                'keterangan' => 'Tidak Bisa Dipakai /Machino Rusak',
            ]
        ];

        DB::table('hidran_kota')->insert($data);
    }
}