<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanjutanAlatPenyelamatanSeeder extends Seeder
{
    public function run()
    {
        $fireman_hood = [
            ['nama_penerima' => 'M. Sanusi Andrian', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Muthalib. Hs', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ade Firnanda Rivai', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adriansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amir Hamza', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arif Masdianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aulia Rahman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Roziardy Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Isharianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra. S', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ja’i', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sujarkoni', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Munir Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nurpan Taupan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Poniadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Saiful Mustofa', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suprapto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wagimin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wakijan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suci Fitriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deden Ramadhan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Eko Perdana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suherman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Riawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Irfan Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Ariandi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Sabta ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Paryono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Deni Pranata', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ranu Prasetio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Surandi Maulana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Eko ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Basopi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Hariyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suryadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Fanani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ishak Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andi Setiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Jhon Husairi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadli', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Syafiq', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hasanudin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Utoyo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Susilo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Rio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muslim', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Khiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rifo Nofriadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Agung. P', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M Idrus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Harmono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kholid', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Heri Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyan Febriatnto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Danil Akbar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masrizal', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riky Restiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arifin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misbah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Iwan Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firdaus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Isnaini', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Thoblawi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Herman Yanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Muammar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Isnaini', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('fireman_hood')->insert($fireman_hood);

        $handy_talky = [
            ['nama_penerima' => 'Kiki, ST', 'jabatan' => 'Sekretaris Dinas', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Azwar, SE', 'jabatan' => 'Kabid Sapra', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Budi Siswanto', 'jabatan' => 'Kabid Damtan', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ardiansyah', 'jabatan' => 'Kabid Pencegahan', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indra Jafrizal', 'jabatan' => 'Kasi Pemadaman', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Harris', 'jabatan' => 'Kasi Pemeliharaan', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hafis', 'jabatan' => 'Danki Mako', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Bambang', 'jabatan' => 'Wadanki', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hermanyanto', 'jabatan' => 'Danton I ', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'jabatan' => 'Danton II', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasianto', 'jabatan' => 'Danton III', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Muammar', 'jabatan' => 'Danpos Albar', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Rusdi', 'jabatan' => 'Danpos Jamkose', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo', 'jabatan' => 'Danpos Jambi Timur', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'jabatan' => 'Danpos Palmerah', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misman', 'jabatan' => 'Danpos Kota Baru', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('handy_talky')->insert($handy_talky);

        $masker_asap = [
            ['nama_penerima' => 'Kepala Dinas ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sekretaris Dinas', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kepala Bidang Pemadaman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kepala Bidang Pencegahan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasi Penyelamatan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasi PKA', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sanusi Andrian', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Muthalib. Hs', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ade Firnanda Rivai', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Isnaini', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amir Hamza', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arif Masdianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aulia Rahman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Isharianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra. S', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ja’i', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sujarkoni', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Munir Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nurpan Taupan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Poniadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Saiful Mustofa', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suprapto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wagimin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wakijan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suci Fitriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deden Ramadhan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Eko Perdana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suherman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Riawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Irfan Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Ariandi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Sabta ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Paryono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Deni Pranata', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ranu Prasetio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Surandi Maulana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Eko ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Basopi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Hariyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suryadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Fanani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ishak Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andi Setiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Jhon Husairi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadli', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Syafiq', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hasanudin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Utoyo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Susilo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Rio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muslim', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Khiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rifo Nofriadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Agung. P', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M Idrus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Harmono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kholid', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Heri Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyan Febriatnto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Danil Akbar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masrizal', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riky Restiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arifin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misbah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Iwan Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Ilham Ardhy', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Safi\'i', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Isnaini', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Thoblawi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Taufik', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Herman Yanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Muammar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Kardela', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmad Veri Riski', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Apriadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adriansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firdaus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amat Ariyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riman Jaya', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ahmad Yani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Benni', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'David Hermansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muji Harnadi ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('masker_asap')->insert($masker_asap);

       // -- INI AWAL PART 2 --
        $sepatu_safety = [
            ['nama_penerima' => 'Rully Kurniawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sanusi Andrian', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ja’i', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Roziardy Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amir Hamza', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suprapto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Munir Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Saiful Mustofa', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adriansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Isharianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ade Firnanda Rivai', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra. S', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Muthalib. Hs', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aulia Rahman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Rusak', 'keterangan' => null],
            ['nama_penerima' => 'Arif Masdianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wagimin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Poniadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sujarkoni', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wakijan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nurpan Taupan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suci Fitriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deden Ramadhan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Eko Perdana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suherman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Riawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Irfan Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Ariandi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Sabta ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Paryono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Deni Pranata', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ranu Prasetio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Surandi Maulana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Eko ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Basopi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Hariyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suryadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Fanani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ishak Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andi Setiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Jhon Husairi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadli', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Syafiq', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hasanudin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Utoyo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Susilo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Rio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muslim', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Khiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rifo Nofriadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Agung. P', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M Idrus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Harmono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kholid', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Heri Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyan Febriatnto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Danil Akbar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masrizal', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riky Restiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arifin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misbah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Darmawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridho Dazrizal ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ferdinand Ronaldo T', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahrizal', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Iwan Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Imron', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nanda', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Ilham Ardhy', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mardian Hasnur', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Pendi Abdullah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Nasir', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Siswanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutarto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ilham Saputra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Leksono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Syukur', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muji Harnadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Husnul Mubarok', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dimas Wahyu. K', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Slamet', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Bayu Sukma', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Vicky', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Redi Julian', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Marjoko', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amid Jaya', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nur Ruwanda', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firdaus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Rusak', 'keterangan' => null],
            ['nama_penerima' => 'M. Isnaini', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Thoblawi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Taufik', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Sufriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ardiyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bunnari', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'David Hermansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Herman Yanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Muammar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wendo. AR', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ahmad Yani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Benni', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Yahya', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Furqon', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Kardela', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmad Veri Riski', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ahmad Sukri Insani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Apriadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amrullah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mukhrim', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Adi Agus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Turman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('sepatu_safety')->insert($sepatu_safety);
     // -- INI AWAL PART 3 --
        $baju_driver_dan_baju_mekanik = [
            ['nama_penerima' => 'DODI PRIA SETIAWAN', 'jabatan' => 'DRIVER TON 1 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'JANUARSYAH', 'jabatan' => 'DRIVER TON 1 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. SOLEH', 'jabatan' => 'DRIVER TON 1 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'HARI CANDRA', 'jabatan' => 'DRIVER TON 1 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'SYAMSURI', 'jabatan' => 'DRIVER TON 1 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'DEBY NOFRIADI', 'jabatan' => 'DRIVER TON 2 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'AGUNG CAHYO', 'jabatan' => 'DRIVER TON 2 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'MUHAROM', 'jabatan' => 'DRIVER TON 2 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'SUPRIATIN', 'jabatan' => 'DRIVER TON 2 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'SARWO EDY', 'jabatan' => 'DRIVER TON 2 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'ARITUA HARAHAP', 'jabatan' => 'DRIVER TON 3 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'RICKY OKTORA', 'jabatan' => 'DRIVER TON 3 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'MUSTAQIM', 'jabatan' => 'DRIVER TON 3 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'EFENDI', 'jabatan' => 'DRIVER TON 3 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. SURYA PRATAMA', 'jabatan' => 'DRIVER TON 3 MAKO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'SUNARYO', 'jabatan' => ' REGU 1 ALAM BARAJO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'FIRMANSYAH', 'jabatan' => ' REGU 2 ALAM BARAJO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'ISTARMAN', 'jabatan' => ' REGU 3 ALAM BARAJO', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'ANTON WIBOWO', 'jabatan' => 'REGU 1 JAMBI TIMUR', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'HADI SURYAWIJAYA', 'jabatan' => 'REGU 2 JAMBI TIMUR', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'RORI ANTONI', 'jabatan' => 'REGU 3 JAMBI TIMUR', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'KMS. RICKO', 'jabatan' => 'REGU 1 JAMKOSE', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'REZA AFRIZAL', 'jabatan' => 'REGU 2 JAMKOSE', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'SANDI SAPUTRA', 'jabatan' => 'REGU 3 JAMKOSE', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'R. MARCURY', 'jabatan' => 'REGU 1 KOTA BARU', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'RIYADI YULIATMOKO', 'jabatan' => 'REGU 2 KOTA BARU', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'ARIF ARTEN', 'jabatan' => 'REGU 3 KOTA BARU', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'SUKARNO', 'jabatan' => 'REGU 1 PALMERAH', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'RANDI SAPUTRA', 'jabatan' => 'REGU 1 PALMERAH', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'MOHD. IRFAN', 'jabatan' => 'REGU 1 PALMERAH', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'ZAKIRIN', 'jabatan' => 'MEKANIK TON I MAKO', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'MAJITO SUGIANTO', 'jabatan' => 'MEKANIK TON II MAKO', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'SUTRIANTO', 'jabatan' => 'MEKANIK TON III MAKO', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('baju_driver_dan_baju_mekanik')->insert($baju_driver_dan_baju_mekanik);

        $baju_tahan_panas_dan_helm_pemadam_kebakaran = [
            ['nama_penerima' => 'M. Sanusi Andrian', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Muthalib. Hs', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ade Firnanda Rivai', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adriansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amir Hamza', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arif Masdianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aulia Rahman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Roziardy Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Isharianto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra. S', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ja’i', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sujarkoni', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Munir Riyadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nurpan Taupan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Poniadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Saiful Mustofa', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suprapto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wagimin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wakijan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suci Fitriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deden Ramadhan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Eko Perdana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suherman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Riawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Irfan Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Ariandi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Sabta ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Paryono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Deni Pranata', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ranu Prasetio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Surandi Maulana', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Eko ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Basopi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Hariyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suryadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Fanani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ishak Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andi Setiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Jhon Husairi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadli', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Syafiq', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hasanudin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Utoyo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Susilo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Rio', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muslim', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Khiyoto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rifo Nofriadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Agung. P', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M Idrus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Harmono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kholid', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Heri Hidayat', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyan Febriatnto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Danil Akbar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masrizal', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riky Restiawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arifin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misbah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Darmawan', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridho Dazrizal ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ferdinand Ronaldo T', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahrizal', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Iwan Effendi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Imron', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nanda', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firdaus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mardian Hasnur', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Pendi Abdullah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Nasir', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Siswanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutarto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ilham Saputra', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2023', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Leksono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Syukur', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muji Harnadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Husnul Mubarok', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dimas Wahyu. K', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Slamet', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Bayu Sukma', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif ', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Vicky', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Redi Julian', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Marjoko', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amid Jaya', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nur Ruwanda', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Ilham Adry', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Isnaini', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Thoblawi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Taufik', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Sufriyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ardiyanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bunnari', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'David Hermansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2022', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riman Jaya', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2021', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Zakirin', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2021', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Herman Yanto', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Muammar', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wendo. AR', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ahmad Yani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Benni', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Yahya', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Furqon', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Kardela', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmad Veri Riski', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ahmad Sukri Insani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => 'Baju Rusak Parah'],
            ['nama_penerima' => 'Bambang Apriadi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amrullah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Adi Agus', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2020', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mukhrim', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '-', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yudi', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '-', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Turman', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '-', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sapi\'i', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '-', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('baju_tahan_panas_dan_helm_pemadam_kebakaran')->insert($baju_tahan_panas_dan_helm_pemadam_kebakaran);
       // -- INI AWAL PART 4 (TERAKHIR) --
        $filter_atau_catridge_masker_asap = [
            ['nama_penerima' => 'Amad Yani', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riman Jaya', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'David Hermansyah', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dody Athoilah. W', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ja\'i', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sanusi Adrian', 'jabatan' => '', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('filter_atau_catridge_masker_asap')->insert($filter_atau_catridge_masker_asap);

        $fire_blanket = [
            ['nama_penerima' => 'M. Hafis', 'jabatan' => 'Danpos Alam Barajo', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Rusdi', 'jabatan' => 'Danpos Jamkose', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo', 'jabatan' => 'Danpos Jambi Timur', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hermanyanto', 'jabatan' => 'Danpos Palmerah', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'jabatan' => 'Danpos Kota Baru', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'jabatan' => 'Danton II Mako', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif Wahyudi', 'jabatan' => 'Driver Komando Ton II Mako  ', 'jumlah' => '2 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Rusdi', 'jabatan' => 'Danpos Jamkose', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firdaus', 'jabatan' => 'Danru Palmerah', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasianto', 'jabatan' => 'Danton III Mako', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febry Roziardy Putra', 'jabatan' => 'Danru Ton I Mako', 'jumlah' => '1 Unit', 'tahun' => '', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('fire_blanket')->insert($fire_blanket);

    }
}