<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PakaianSiagaJaketSeeder extends Seeder
{
    public function run()
    {
        $baju_siaga_celana_training = [
            ['nama_penerima' => 'Mustari Affandi', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kiki', 'ukuran' => 'XXL', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Budi Siswanto ', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Azwar, SE', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ardiansyah', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indra Jafrizal', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Harris', 'ukuran' => 'XXXL', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Binsar. F. G. Butarbutar', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suhermanto, SE', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dewi Sartika', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tinuk', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tri Hartati', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deki Irawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Bambang E.', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amir Hamza', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dodi Pria Setiawan', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suci Fitriyanto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deden Ramadhan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ardiyanto ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sanusi Andrian', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Januarsyah ', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Eko Perdana', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suherman ', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wahyudi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ja’i ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Soleh', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Taufik', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Riawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Henderiono', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Candra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Syamsuri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Alfian. WH.', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Zakirin ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Luqman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deby Nofriadi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Irfan Wahyudi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Roziardy Putra', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agung Cahyo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Ilham. AR.', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Ariandi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hidayat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suprapto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muharom', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Sabta Kusuma', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Isharianto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indriyanto Adi Saputra', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Supriatin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sarwo Edy', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif Wahyudi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Majito Sugianto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rikky Suhendar ', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Saipul Mustopa', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aritua Harahap', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Paryono', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Apriadi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Dheni Pranata', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ade Firnandi Rivai', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ricky Oktora', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ranu Prasetyo', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Munirriyadi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Iwan Effendy', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adriansyah', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mustaqim', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Surandi Maulana', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Sufriyanto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Efendi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Surya Pratama', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Pikri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhazirin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutriyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridho Dasrizal', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Rusdi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nurpan Taupan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Ricko Apriansyah', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rifo Nofriyady', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Agung P.', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Redi Julian', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'David Hermansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Isnaini', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Afrizal', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Febri Harmono', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Kardela', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bunnari', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Idrus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Thoblawi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sandi Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Yahya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Heri Hidayat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kholid Is', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Sukri Insani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tisrianti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Susi Ermawati', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hermanyanto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sukarno', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ishak Efendi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andi Setiawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wendo. AR', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firdaus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Randi Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riman Jaya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ahmad Yani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Furqon', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rd. Jhon Husairi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadli Asril', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mohd. Irfan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Syafiq', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Nasir', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Said Hasan Basri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hasanudin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Darmawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ellysa Tatinia', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yuliana', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wagimin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Anton Wibowo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyan Febrianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wir Syarif', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Danil Akbar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahrizal', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Poniadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hadi Surawijaya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riki Restiawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Marjoko', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nanda', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masrizal Oktavianes ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sujarkoni', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rori Antoni', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arifin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amid Jaya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dodi A. W.', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misbah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suheni ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tuti Alawiyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'R. Mercury', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Basopi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmad Veri Rizky', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Eko Novian', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Turman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wiyoto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyadi Yuliatmoko', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Haryanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sapi’i', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yudi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suryadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aulia Rahman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arif Arten', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Benni', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Fanani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Slamet', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Putra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indra Sulastri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Susriani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Muammar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wakijan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sunaryo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Utoyo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Susilo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mukrim', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Husnul Mubarok', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firmansyah ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amat Ariyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muslim', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amrullah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Rio', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Muthalib', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Istarman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aditya Prasetyo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Kiyoto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Anwar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mira Mulyana ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sri Weti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Monalisa', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'S. M. Ningsih', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masdede Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kaspul', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'H. Mubarok', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sandi Priyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rd. Syahrial', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridwan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Beni Asril', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juarti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Lesti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sinta', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmat ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Imron', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutrimo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misman ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sahri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Budi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mardi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agung. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridwansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rinaldo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fitriadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suzanna', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Neni Maryanti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muziat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aman. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Jaya Mardiansyah ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yogi Wanda Putra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ferdinand Ronaldo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Johan Harjito', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdi Mulya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ezwin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Noviyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sabari', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. kadir', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mutasor', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bella Dona', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahmi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadilla', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dian Ariansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ari Arianus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mohd. Faizal Hidayat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Diky Sucipto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Robby Pradiansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Yusuf', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Fahrianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Welly Yudhantoro', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Al Chudri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yani Susanti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmi Feliana', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sri Kurniawati', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hamidah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Patmawati', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dinda Nadila', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Anggraini', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deni Gusrianti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nency Dwiyana Putri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rosyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Adi Agus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutarto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Siswanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ilham Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Syukur', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muji Harnadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nur Ruwanda', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mardian Hasnur', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dimas Wahyu', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Panji Agung', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bayu Sukma', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Leksono', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdurrahman Anwar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rully Kurniawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arif Masdianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Yanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hapis', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deka ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Viky', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ismail', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dody. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahreza', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Pendi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Khairudin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Dody', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andri Wahyudi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('baju_siaga_celana_training')->insert($baju_siaga_celana_training);

        $jaket_waterproof = [
            ['nama_penerima' => 'Mustari Affandi', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kiki', 'ukuran' => 'XXL', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Budi Siswanto ', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Azwar, SE', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ardiansyah', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indra Jafrizal', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Harris', 'ukuran' => 'XXXL', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Binsar. F. G. Butarbutar', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suhermanto, SE', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dewi Sartika', 'ukuran' => 'XL', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tinuk', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tri Hartati', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deki Irawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Bambang E.', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amir Hamza', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dodi Pria Setiawan', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suci Fitriyanto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deden Ramadhan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ardiyanto ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sanusi Andrian', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Januarsyah ', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Eko Perdana', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suherman ', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wahyudi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ja’i ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Soleh', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Taufik', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Riawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Henderiono', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Candra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Syamsuri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Alfian. WH.', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Zakirin ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Luqman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Sugiono', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deby Nofriadi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Irfan Wahyudi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Febri Roziardy Putra', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agung Cahyo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Ilham. AR.', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Ariandi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hidayat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suprapto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muharom', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hari Sabta Kusuma', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Isharianto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indriyanto Adi Saputra', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Supriatin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sarwo Edy', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif Wahyudi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Majito Sugianto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rikky Suhendar ', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kasianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Saipul Mustopa', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aritua Harahap', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Paryono', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bambang Apriadi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Dheni Pranata', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ade Firnandi Rivai', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ricky Oktora', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ranu Prasetyo', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Munirriyadi', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Iwan Effendy', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adriansyah', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mustaqim', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Surandi Maulana', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Sufriyanto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Efendi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Surya Pratama', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Pikri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhazirin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutriyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridho Dasrizal', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Rusdi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nurpan Taupan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Ricko Apriansyah', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rifo Nofriyady', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Agung P.', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Redi Julian', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'David Hermansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Isnaini', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Afrizal', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Febri Harmono', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Kardela', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bunnari', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Idrus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dedi Thoblawi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sandi Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Yahya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Heri Hidayat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kholid Is', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Sukri Insani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tisrianti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Susi Ermawati', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hermanyanto', 'ukuran' => 'L', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sukarno', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ishak Efendi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Arif', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andi Setiawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wendo. AR', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firdaus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Randi Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riman Jaya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ahmad Yani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Furqon', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rd. Jhon Husairi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadli Asril', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mohd. Irfan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Syafiq', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Nasir', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Said Hasan Basri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hasanudin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Darmawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ellysa Tatinia', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yuliana', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wilopo ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wagimin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Anton Wibowo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyan Febrianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wir Syarif', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Danil Akbar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahrizal', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Poniadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hadi Surawijaya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riki Restiawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Marjoko', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nanda', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masrizal Oktavianes ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Sujarkoni', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rori Antoni', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arifin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amid Jaya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dodi A. W.', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misbah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suheni ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Tuti Alawiyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Wahyudi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'R. Mercury', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Basopi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmad Veri Rizky', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Reza Eko Novian', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Turman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Wiyoto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Riyadi Yuliatmoko', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agus Haryanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sapi’i', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yudi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suryadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aulia Rahman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arif Arten', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Benni', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. Fanani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Slamet', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Putra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Indra Sulastri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Susriani', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kms. Muammar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Wakijan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sunaryo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Utoyo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Edi Susilo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mukrim', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Husnul Mubarok', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hendra. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Firmansyah ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amat Ariyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muslim', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Amrullah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Rio', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Muthalib', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Istarman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aditya Prasetyo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Adi Kiyoto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Anwar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mira Mulyana ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sri Weti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Monalisa', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'S. M. Ningsih', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Masdede Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Kaspul', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'H. Mubarok', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sandi Priyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rd. Syahrial', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridwan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Beni Asril', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Juarti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Lesti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sinta', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmat ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Imron', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutrimo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Misman ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sahri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Budi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mardi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Agung. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ridwansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rinaldo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fitriadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Suzanna', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Neni Maryanti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muziat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Aman. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Jaya Mardiansyah ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yogi Wanda Putra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ferdinand Ronaldo', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Johan Harjito', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdi Mulya', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ezwin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Noviyanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sabari', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'A. kadir', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mutasor', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bella Dona', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahmi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fadilla', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dian Ariansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ari Arianus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mohd. Faizal Hidayat', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Diky Sucipto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Robby Pradiansyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muhammad Yusuf', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Fahrianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Welly Yudhantoro', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Al Chudri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Yani Susanti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rahmi Feliana', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sri Kurniawati', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Hamidah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Patmawati', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dinda Nadila', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dwi Anggraini', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deni Gusrianti', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nency Dwiyana Putri', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rosyah', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Feri Adi Agus', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Sutarto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Siswanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ilham Saputra', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdul Syukur', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Muji Harnadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Nur Ruwanda', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Mardian Hasnur', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dimas Wahyu', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Panji Agung', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Bayu Sukma', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Teguh Leksono', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Abdurrahman Anwar', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rully Kurniawan', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Arif Masdianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Rudi Yanto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Hapis', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2025', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Deka ', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Viky', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Ismail', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dody. S', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Fahreza', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Pendi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Khairudin', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'M. Dody', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Andri Wahyudi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2026', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Doni Sumatriadi', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Julianto', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
            ['nama_penerima' => 'Dadan Sulaiman', 'ukuran' => 'M', 'jumlah' => '1', 'tahun' => '2024', 'kondisi' => 'Baik', 'keterangan' => null],
        ];
        DB::table('jaket_waterproof')->insert($jaket_waterproof);
    }
}