<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SepatuSafetySeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['nama_penerima' => 'Rully Kurniawan', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Kasianto', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M. Sanusi Andrian', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ja’i', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Febri Roziardy Putra', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Amir Hamza', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Juliansyah Sulaiman', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Suprapto', 'sepatu_safety' => 1, 'tahun' => 2019, 'keterangan' => ''],
            ['nama_penerima' => 'Munir Riyadi', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Ragil Ade Nugroho', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Saiful Mustofa', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Adriansyah', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Feri Isharianto', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Ade Firnanda Rivai', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Hendra. S', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Abdul Muthalib. Hs', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Kms. Rahmad Riyadi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Aulia Rahman', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Wiyoto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Arif Masdianto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dwi Salyo Prabowo', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Wagimin', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Poniadi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Sujarkoni', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Wakijan', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Nurpan Taupan', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Suci Fitriyanto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Deden Ramadhan', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Eko Perdana', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Suherman', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Riawan', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Wahyudi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Irfan Wahyudi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Yoga Tedy Rusady', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Rudi Ariandi', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M. Hidayat', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Hari Sabta ', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Indriyanto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Paryono', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M. Deni Pranata', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ranu Prasetio', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Surandi Maulana', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Reza Eko ', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Basopi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Agus Hariyanto', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Suryadi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'A. Fanani', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Adi Putra', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ishak Effendi', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Andi Setiawan', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Jhon Husairi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Fadli', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Syafiq', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Hasanudin', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Rudi Utoyo', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Edi Susilo', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Muhammad Rio', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Muslim', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Apriyan Pratama Putra', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Adi Khiyoto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Rifo Nofriadi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dedi Agung. P', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M Idrus', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Febri Harmono', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Kholid', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Heri Hidayat', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Riyan Febriatnto', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Danil Akbar', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Masrizal', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Riky Restiawan', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Arifin', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Misbah', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M. Arif Wahyudi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Darmawan', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ridho Dazrizal ', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ferdinand Ronaldo T', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Fahrizal', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Iwan Effendi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Imron', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Nanda', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Ilham Ardhy', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Mardian Hasnur', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Pendi Abdullah', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Nasir', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Siswanto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Sutarto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ilham Saputra', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Teguh Leksono', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Abdul Syukur', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Muji Harnadi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Husnul Mubarok', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dimas Wahyu. K', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Slamet', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Bayu Sukma', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Arif ', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Vicky', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Redi Julian', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Edi Marjoko', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Amid Jaya', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Nur Ruwanda', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Firdaus', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Bambang Sugiono', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'M. Isnaini', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dedi Thoblawi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Taufik', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Teguh Sufriyanto', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Ardiyanto', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
            ['nama_penerima' => 'Bunnari', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'David Hermansyah', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Herman Yanto', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Kms. Muammar', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Dwi Wahyudi', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Wilopo', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Wendo. AR', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ahmad Yani', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Benni', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Yahya', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Furqon', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'M. Kardela', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Rahmad Veri Riski', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Ahmad Sukri Insani', 'sepatu_safety' => 0, 'tahun' => null, 'keterangan' => ''],
            ['nama_penerima' => 'Bambang Apriadi', 'sepatu_safety' => 1, 'tahun' => 2024, 'keterangan' => ''],
        ];

        // Memasukkan array ke dalam tabel database
        DB::table('sepatu_safety')->insert($data);
    }
}